# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(max_length=6)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('imei', models.CharField(blank=True, max_length=15)),
                ('bt_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
