# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_auto_20170927_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLocalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField()),
                ('group', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='LocationDensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('location', models.CharField(max_length=12)),
                ('density', models.IntegerField(default=0)),
            ],
        ),
    ]
